/* 
* 유저
*/

CREATE TABLE IF NOT EXISTS users (
	id TEXT PRIMARY KEY, -- uuid
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	email TEXT NOT NULL UNIQUE,
	social TEXT,
	nickname TEXT
);